title: "穿越这无限世界-BabyKing's Blog"

highlighter: rouge

kramdown:
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    line_numbers: false # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

paginate: 5
paginate_path: "blog/page:num"

# Google Analytics
ga_track_id: UA-127077562-1            # Format: UA-xxxxxx-xx
ga_domain: 

# Gitalk settings
comment_gitalk_clientId: ff150298319a020d8df9
comment_gitalk_clientSecret: 40e533e2734bc7444e08a2212000c2c6cbac9fcf
comment_gitalk_repo: babyking.github.io
github_username: babyking