title: "穿越这无限世界-BabyKing's Blog"

highlighter: rouge

kramdown:
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Google Analytics
ga_track_id: UA-127077562-1            # Format: UA-xxxxxx-xx
ga_domain: 